### PR TITLE
snap: migrate to `base: core24`

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
```
$ graphics-test-tools.glmark2-es2
/snap/graphics-test-tools/389/bin/gpu-2404-wrapper: 16: exec: /snap/graphics-test-tools/389/graphics/bin/gpu-2404-provider-wrapper: not found
```

**Comment by Saviq** [comment]
> ```
> $ graphics-test-tools.glmark2-es2
> /snap/graphics-test-tools/389/bin/gpu-2404-wrapper: 16: exec: /snap/graphics-test-tools/389/graphics/bin/gpu-2404-provider-wrapper: not found
> ```

Rebuilding, this picked up a broken version of the script, fixed here:

https://github.com/canonical/gpu-snap/commit/929a4228ebeb17dd1cb82c48346b192ac02ac1a3

**Comment by AlanGriffiths** [comment]
After rebuild...
```
$ WAYLAND_DISPLAY=wayland-2 graphics-test-tools.glmark2-es2
/snap/graphics-test-tools/407/bin/gpu-2404-wrapper: 16: exec: /snap/graphics-test-tools/407/gpu-2404/bin/gpu-2404-provider-wrapper: not found
```

**Comment by Saviq** [comment]
> After rebuild...

You can see why I decided to keep all those be `gpu-2404`... hunting for all versions of `-core22`, `-core`, `graphics` is messing with me. Fixed.

**Review by AlanGriffiths — APPROVED** [review]
OK (modulo the hacks required for the current build chain)

**Review by AlanGriffiths — APPROVED** [review]
LGTM

**Pull request merged**
